name: Install SFML
description: Install Simple and Fast Multimedia Library
inputs:
  sfml:
    description: The version of SFML to install ("latest", "nightly", "2.5.1")
    default: latest
  config:
    description: The configuration of the build ("Release", "Debug")
    default: Release
  useStatic:
    description: Use static linking? Only used if installing from source.
    default: false
  generatorPlatform:
    description: Specifiy the platform name for the CMake generator (see documentation for cmake -A)
    default: "default"
  token:
    description: Personal access token (auto-populated)
    default: ${{ github.token }}
outputs:
  sfml:
    description: The actual version of SFML that was installed
  path:
    description: The directory where SFML was installed, so you can use '[path]/include' etc.
runs:
  using: node16
  main: index.js
